### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by rr326** [thomasahle/sunfish#17]
I tried this with python 2, python 3, from command line and within ipython and all get approximately the same thing.  Maybe user error. (No pypy though.)

    Your move: e6
    Traceback (most recent call last):
      File "chess.py", line 388, in <module>
        main()
      File "chess.py", line 365, in main
        move = parse(crdn[0:2]), parse(crdn[2:4])
      File "chess.py", line 345, in parse
        fil, rank = ord(c[0]) - ord('a'), int(c[1]) - 1
    IndexError: string index out of range

**Comment by thomasahle** [comment]
There are now better error messages for this. Hope it helps :)
