### ISSUE TITLE
Error: pop takes two arguments (line 195)

### ISSUE THREAD

**Issue by zfrenchee** [thomasahle/sunfish#22]
This code seems fishy: 
```
    # We save the found move together with the score, so we can retrieve it in
    # the play loop. We also trim the transposition table in FILO order.
    # We prefer fail-high moves, as they are the ones we can build our pv from.
    if entry is None or depth >= entry.depth and best >= gamma:
        tp[pos] = Entry(depth, best, gamma, bmove)
        if len(tp) > TABLE_SIZE:
            tp.pop()
    return best
```

tp is an ordereddict, so it does have an additional method popitem() which will pop the last item from the dict. Otherwise, the pop method requires two arguments: the key and a default value to pop if the function can't find the key in the dictionary. This is raising errors for me.

**Comment by zfrenchee** [comment]
Sorry folks, I'm back to my computer. Has this been resolved? If not I'll send you that pull request.

**Comment by thomasahle** [comment]
Sorry, I've been away as well, the fix works perfectly, send a request and I'll pull it to main.
