### ISSUE TITLE
King puts itself in check

### ISSUE THREAD

**Issue by prcoder** [thomasahle/sunfish#24]
When I ran selfplay() in test.py I noticed the game ended by king capture. See screenshot, where the black king moves g7-g8 and puts itself in check:

![g7g8](https://cloud.githubusercontent.com/assets/10849636/6058747/874b1302-ad2a-11e4-93dc-3a0fb69611e8.png)

It can also be reproduced by letting Sunfish search for black in this position:
    `pos = xboard.parseFEN('R7/6k1/8/8/8/8/8/7K b - - 0 1')`
where g7-g8 is immediately found as best move, but it also puts the black king in check.

As Sunfish borrows from Micro-Max which states:
_"Before we discuss castling, it is good to point out that micro-Max is a King-capture engine: At any level it generates all pseudo-legal moves, including those that put his own King in check. Since this is a condition that depends on which moves the opponent has, it seems more logical to test it on the next ply, when we generate the opponent's moves anyway. Usually all opponent's moves are generated before micro-Max starts to think about any of them, and if a King capture is found the branch is aborted and the caller is informed (by the move's score) that the move was an illegal one."_

I think somewhere in the bound() or genMoves() code this branch abortion must be added for check cases.

**Comment by thomasahle** [comment]
Interesting. Does this happen every time it finds itself in an impossible situation?

**Comment by prcoder** [comment]
This happens because genMoves() also generates invalid moves: there is no code that discards moves that put itself in check. As mentioned in the Micro-Max comment, those moves should be discarded on the next ply (where the King is captured). However, this doesn't happen in the Sunfish code.

**Comment by thomasahle** [comment]
Correct, but mostly these moves should never be played, because sunfish will detect it's king will then be captured.

What I mean is, how repeatable is the situation where it actually moves illegally?

**Comment by prcoder** [comment]
It seems it usually happens when there are not many moves and King moves are being considered. Because of the pst tables, it prefers to move the King towards b1 or g1 (or b8, g8 for black).
In those situations sunfish doesn't seem to detect cases where the King can be captured.

As mentioned above, this simple position is typical and reproduces the error:

`pos = xboard.parseFEN('R7/6k1/8/8/8/8/8/7K b - - 0 1')`

**Comment by prcoder** [comment]
I found something that prevents 'self-check' in lots of cases, but unfortunately not in all. Something goes wrong in the nullscore handling. When line 260 in sunfish.py is changed into:

   ` nullscore = -bound(pos.rotate(), 1-gamma, depth-3) if depth >= 0 else pos.score`

so >=0 instead of >0 then the King doesn't put itself in check in most cases. However, it might do so when capturing a piece as in the position below, where it will play h3xg2:

` pos = xboard.parseFEN('6k1/1p6/1q4pp/p3Pp2/8/8/5RP1/4R1K1 w - - 0 46')`

![image](https://cloud.githubusercontent.com/assets/10849636/6168656/54f9ea3e-b2c7-11e4-8d51-32a677468194.png)

**Comment by thomasahle** [comment]
Right, it's dangerous to do null-move while in check.
Problem is, we have no way of knowing if we're in check, before we've generated moves.
How do we solve that? If it mostly solves the problem to do `depth >= 0`, I'm not against merging it, but a full solution would be nice :-)
