### ISSUE TITLE
Check for stalemate

### ISSUE THREAD

**Issue by ugoertz** [thomasahle/sunfish#28]
In [line 286](https://github.com/thomasahle/sunfish/blob/master/sunfish.py#L286):

```python
if depth > 0 and best <= -MATE_VALUE is None and nullscore > -MATE_VALUE:
```

I do not get what the "is None" is doing - it looks to me as if it should be omitted. *Edit*: In fact, the "is None" was necessary in the previously used check for stalemate, and should have been deleted in [this commit](https://github.com/thomasahle/sunfish/commit/33387f68fb421199fb3b4169a5cef2856ebf96db).

Furthermore, there are stalemate positions without pseudo-legal moves, so maybe it would be better to additionally check whether pos.genMoves() is empty. *Edit:* Since best is initialized appropriately, this is unnecessary.

Thanks for your work, it is a pleasure to study the sunfish code.

**Comment by thomasahle** [comment]
Hi ugoertz! I can't quite figure out what the None is doing there either. It doesn't even seem to make sense semantically. Sometimes Python allows us to shoot ourselves in the feet a little too aggressively :-) 

If you remove it, run some tests and send a pull request, I'll be happy to include it.

**Comment by ugoertz** [comment]
Thanks for the reply. I just created a pull request.

However, as noted in the commit messages, checking for stalemate remains kind of problematic: I only could confirm that the change does help when I switched off the nullmove pruning. For example, even in the first line of tests/stalemate2.fen, the draw is not detected when nullmove pruning is in effect, because the check for stalemate is never reached anyway.

Not sure what to do (or maybe I am just missing something?).

With nullmove pruning turned off, removing the "is None" is effective and the first two lines of stalemate2.fen do run through successfully. For those of the other lines which I looked at, the draw is still not detected: The check for stalemate does work, but if I understand correctly, we would at least need a check for threefold repetition.

**Comment by thomasahle** [comment]
Sweet, thanks :-)
