### ISSUE TITLE
Why is the transposition table trimmed in a FILO order?

### ISSUE THREAD

**Issue by Recursing** [thomasahle/sunfish#37]
Wouldn't it make more sense to trim it in a FIFO order?
The oldest positions should be the least relevant ones, shouldn't they?

**Comment by thomasahle** [comment]
Good catch! That certainly seems more natural to me as well. Simply adding a "last=True" argument to tp.popitem() should suffice. Have you tried testing how it affects sunfish' strength?

**Comment by Recursing** [comment]
As you said in Issue 22, it's very rare to fill the transposition table, so I wouldn't know how to quantify the difference in strength.
I guess that without "last=True" after the table was filled sunfish would just play without updating it, and after a few moves it should be like playing with no transposition table

**Comment by Recursing** [comment]
It should be last=False, btw
https://docs.python.org/2/library/collections.html#collections.OrderedDict

**Comment by thomasahle** [comment]
It also turned out that OrderedDict didn't refresh items on read and write. Thus we actually need the full LRU Cache in the latest version.

**Comment by Recursing** [comment]
Yeah, I didn't think about that.
Still, something like zobrist hashing might remove the practical need for the added complexity of removing keys from the table, I really doubt someone will reach 1e9 nodes with sunfish
