### ISSUE TITLE
Remove player suicide move from the pos.gen_moves()

### ISSUE THREAD

**Issue by xinyu0791** [thomasahle/sunfish#40]
As chess rule only has checkmate, never kill the king, so player move causes king die is illegal. Removing the player move  that lets AI check king from the possible move list will be easy to judge the game is checkmate or drawn.

**Comment by thomasahle** [comment]
This could probably be done in a single line, so I suppose it is alright to include. Feel free to submit pull request.
Note however, that for the most pleasant playing experience, you should use sunfish in a GUI like PyChess, Xboard or Arena.

**Comment by xinyu0791** [comment]
Yes, sunfish is an amazing chess engine. And i have test removing suicide move in my code, well, in the last layer of alpha-beta, to evaluate the situation, give king die a very large or small value is very easy to get the situation value. However, i think there should be a check of checkmate in the middle layer of search tree, because without it,if king is captured, the iteration will still go to the next layer and don't return immediately. In an other word,  the tree is not a tree in which all branch have the same deep.  Maybe sunfish have included it, and i just not find it or understand it. Can you help me find these codes? Thanks.

**Comment by thomasahle** [comment]
I don't think any of the search code needs to be changed. But in the small "user interface part", this line: https://github.com/thomasahle/sunfish/blob/master/sunfish.py#L434 could be made to check that the user move is not only 'pseudo legal', but also doesn't put their own king in danger.
