### ISSUE TITLE
Mate bug

### ISSUE THREAD

**Issue by ctesiphon** [thomasahle/sunfish#41]
Hi,

The computer said that I was mated when I was not (see screencapture).
I was playing white.

![capture du 2017-01-23 14-13-51](https://cloud.githubusercontent.com/assets/5954933/22205746/7c6fc12e-e178-11e6-8379-85b019b85b50.png)

**Comment by thomasahle** [comment]
It looks like you cheated, by castling while in check, and sunfish wouldn't have any of it ;-)
This is a good case in favor of https://github.com/thomasahle/sunfish/issues/40

**Comment by ctesiphon** [comment]
Ok, I suppose that this program is not for me since : 

- My eyesight is not very sharp
- The board is not perfectly geometrical, so you can miss some threats (like the Queen on h4)
- I am the worst player imaginable, I need the computer to tell me when I try to play an illegal move...

It's a shame though because It's a great app anyway.

**Comment by thomasahle** [comment]
Unless you specifically want a terminal based app, I can recommend using an interface, such as PyChess or Arena. They let you play against sunfish, while getting a real graphical user interface.
