### ISSUE TITLE
connect to pychess

### ISSUE THREAD

**Issue by qwdm** [thomasahle/sunfish#45]
How to use sunfish with pychess?

**Comment by thomasahle** [comment]
You should add an entry like
```
{"protocol": "xboard",
         "name": "/some/path/sunfish/xboard.py",
         "country": "dk",
         "vm_name": PYTHONBIN,
         "vm_args": ["-u"]}
```
to your enginesNest.py file. Or the engines.json file that PyChess creates. It might also be possible to do using the graphical interface. I can't really help you more than that.
