### ISSUE TITLE
Ansi Board?

### ISSUE THREAD

**Issue by jdmayfield** [thomasahle/sunfish#47]
Cool!  Love the Unicode pieces.  Any chance of adding ansi codes for background colors to make the board look as good as the pieces?  Would be killer if the chessboard was checkered.  Looks great, but that would really top it off (also easier to play-- I have trouble tracking the dots diagonally).

Another idea, use the "alternate screen" (application mode) and add ansi support for mouse clicks and arrow keys, at least for xterm compatible terminals.  On mobile terms with touch support, it would make a really cool mini-app.
 
Anyway, like what you did here.

**Comment by thomasahle** [comment]
We have talked before about having a 'pretty.py' module that you can run, which has a nicer text (or graphical) interface. If you'd like to have a stab at it, feel free to send a push request!

**Comment by thomasahle** [comment]
This is now in `fancy.py`.
