### ISSUE TITLE
Piece Table Value Selection

### ISSUE THREAD

**Issue by Daspy11** [thomasahle/sunfish#51]
Hi,

For a school project, I am working to optimize the piece table values for sunfish using particle swarm simulation to find the best results. For my research, I'm interested to know how the values currently used in the engine were selected. Were they just found through human testing through trial and error or were they found using an existing algorithm? I wonder how close they are to optimal.

If somebody could help me with the reasoning that would be appreciated.

Additionally, if the creator would be willing to answer a few interview questions via email it would be HUGELY appreciated - project specs say there needs to be an interview somewhere in there ¯\_(ツ)_/¯

Thanks.

**Comment by thomasahle** [comment]
Hi Daspy,
I wrote about how the sunfish psts are done here http://talkchess.com/forum3/viewtopic.php?f=7&t=64972&p=728789&sid=833ce03ca635255058a0ff3f9feced3c#p728789

If you come up with some new tables, you can use the arena functionality in sunfish's utils to test if they are better than the current ones.

**Comment by Daspy11** [comment]
Great, that's super helpful. Thanks.
