### ISSUE TITLE
print_pos with pieces with opposite colours

### ISSUE THREAD

**Issue by mphuget** [thomasahle/sunfish#53]
Hello everyone, 

Just cloned the Git repo and try to use it, I got the opposite when printing the board with print_pos, rank 1 is black and rank 8 is white. To see correct results on console, I swapped the letters in uni_pieces, especially since it reflects now how FEN notation is written, capital letters for white and small letters for black. 

Hope that helps

**Comment by Recursing** [comment]
Do you happen to have a terminal with black text on a white background? I don't think there's a simple way for sunfish to detect this, and most people have a terminal with white text on a dark background

**Comment by thomasahle** [comment]
As Recursing says, most people have white on black terminals.
I know this is against the Unicode intention.
Suggestions for general solutions are welcome, but until now nobody has had any ideas.

**Comment by Recursing** [comment]
Maybe we can use ANSI escape codes?
It would also allow to print dark and light squares, I can make a PR

**Comment by thomasahle** [comment]
It could work. ANSI codes have a tendency to be really obscure though, which might obfuscate the program, unless they are tucked away in some class/library.
In general, it seems counterproductive to add too much "playing" code to sunfish, when one can just use a GUI or play your Rust version online for a much better user interface.
But maybe it can be done in a really nice way :-)

**Comment by Recursing** [comment]
An idea would be simply something like

```
def print_pos(pos):
    print()
    uni_pieces = {
        "r": "♜", "n": "♞", "b": "♝", "q": "♛", "k": "♚", "p": "♟",
        "R": "♖", "N": "♘", "B": "♗", "Q": "♕", "K": "♔", "P": "♙", ".": "·",
    }
    start_formatting = "\x1b[0;30;107m" # black letters on white background
    end_formatting = "\x1b[0m"
    for i, row in enumerate(pos.board.split()):
        print(8 - i, start_formatting, " ".join(uni_pieces.get(p, p) for p in row), end_formatting)
    print("   a b c d e f g h", "\n\n")
```

doesn't seem too obscure

**Comment by thomasahle** [comment]
Ok tried it out. I'm still a bit on the fence though :-)
I guess it looks a bit clearer? But when I've asked people which they prefer, they mostly say the white on black.

<img width="576" alt="Screen Shot 2019-07-26 at 21 18 46" src="https://user-images.githubusercontent.com/946355/61992909-d0ee3100-b064-11e9-9e65-2823bd57d31e.png">
<img width="638" alt="Screen Shot 2019-07-26 at 21 19 15" src="https://user-images.githubusercontent.com/946355/61992910-d0ee3100-b064-11e9-85b3-ccaa6d508769.png">

I also realised https://github.com/thomasahle/sunfish/issues/47 added a pull request for a checkered board. Lots of options here :-)

**Comment by Recursing** [comment]
I don't like the checkered board with square color shown only on empty squares (like in your screenshots). Everything else seems fine, as well as something like #47 (which might be simplified to reduce line number with the usual lambda trick used in the rest of the codebase)

Do you have any preference / think it would be reasonable to add it in master (even just white on black)?

**Comment by thomasahle** [comment]
Ok, I tried a new version that is actually kinda nice. At least I can play a lot faster like this. Less time spent trying to figure out the colours of my bishops.
I still think it makes more sense to add it to a separate module, called play.py or something, so I might do that.
My only worry is that this happens to look good on my setup, but won't for other people.

<img width="345" alt="Screen Shot 2019-07-27 at 13 11 34" src="https://user-images.githubusercontent.com/946355/61993726-34ca2700-b070-11e9-9a4d-ae38b4ea5c39.png">

**Comment by Recursing** [comment]
I can test it on a few setups, I think this table https://en.wikipedia.org/wiki/ANSI_escape_code#Colors is a reliable reference

**Comment by thomasahle** [comment]
I pushed the code to [fastchess](https://github.com/thomasahle/fastchess) (been working more on that for the past couple of days), but if it works on your setups we can port it back to sunfish.

**Comment by Recursing** [comment]
I'm making some tests using this: https://gist.github.com/Recursing/4837fe2ad1921286cf299145367b00f5

Using 4-bit colors
![image](https://user-images.githubusercontent.com/6978200/62045128-1d1bab80-b1f4-11e9-96c2-d03c1ca8fec6.png)
I think the problem is that some terminals render "Bright White" (107) the same color as "White" (47)

Using 8-bit colors for board squares
![image](https://user-images.githubusercontent.com/6978200/62045066-f3628480-b1f3-11e9-9fb7-0b70d44805aa.png)

Other terminals, (some don't have font support for chess pieces)
![image](https://user-images.githubusercontent.com/6978200/62048106-8e129180-b1fb-11e9-8036-c05908cc745b.png)


I think windows might be a problem, though, especially old versions that I have no way to test (see https://stackoverflow.com/questions/16755142/how-to-make-win32-console-recognize-ansi-vt100-escape-sequences )

**Comment by Recursing** [comment]
Windows of course doesn't support the standard :(, supporting windows would add some complexity, 
> On Windows, Colorama strips these ANSI characters from stdout and converts them into equivalent win32 calls for colored text. On other platforms, Colorama does nothing. 

![image](https://user-images.githubusercontent.com/6978200/62048446-6ec83400-b1fc-11e9-901a-fbaaba270205.png)

**Comment by thomasahle** [comment]
That looks surprisingly consistent!
So you're saying if we use 8bit colors it works everywhere but windows?
What do you think about getting rid of the .'s? Seems we can get the checkerboard with background colors well enough.

**Comment by Recursing** [comment]
> So you're saying if we use 8bit colors it works everywhere but windows

I haven't been able to find a counterexample, and the Colorama source seems to suggest the same

> What do you think about getting rid of the .'s?
For me it's the same, would keep them on windows

**Comment by thomasahle** [comment]
I just saw this fancy terminal chess interface: https://github.com/nickzuber/chs :-D

**Comment by Recursing** [comment]
Saw it as well on r/chess
Pretty sure it doesn't work on Windows as well since it uses the same
escape codes

**Comment by thomasahle** [comment]
The [play_chess.py](https://github.com/thomasahle/fastchess/blob/master/play_chess.py) script in fastchess allows playing with any xboard or uci engine using an engines.json file: `python play_chess.py sunfish`. This also allows playing with black against sunfish and playing sunfish vs. sunfish.

I don't know if the script would be better off in its own project though, or how we make it easy to find from sunfish...

**Comment by thomasahle** [comment]
I have added the play_chess script directly to the sunfish repository as `fancy.py`. Please add any new GUI features to that.
