### ISSUE TITLE
Unreadable variable names

### ISSUE THREAD

**Issue by Recursing** [thomasahle/sunfish#57]
Is there a reason the code uses variable names like "pst" instead of "piece_square_tables", "i" instead of something like "from_index", "j" instead of something like "to_index", "wc" istead of "my_castling", "bc" instead of "opponent_castling" and so on?

I think it makes the codebase less readable without decreasing the line count, is it just something inherited from the golfed programs that inspired this?

Also, could we use `black` or `autopep8` or similar formatters to make the source prettier and more consistent?

**Comment by abhinuvpitale** [comment]
Adding a flake8 test would help this codebase.

**Comment by thomasahle** [comment]
I agree with you in general, and it's possible that the code should be rewritten that way. For this project I have instead tried to keep everything small, but consistent. Having longer variable names would make some lines too long, and I don't want to split them up.

I agree that some documentation would be nice though. Like wc means "white casting", bc "black castling", i and j are always "from square" and "too square", p and q are "from piece" and "too piece".

**Comment by Recursing** [comment]
I think names like `i` and `j` would be very easy to improve, would you be willing to accept a pull request that tries to improve readability without breaking the 80 character limit?

Also using black or autopep8 would make the code more consistent without impacting the line number

**Comment by thomasahle** [comment]
Fair, better names for `i` and `j` are a good idea. Maybe `fs`, `ts` to fit with the convention? :-)

I think autopep8 and black will disagree with the use of inline `if`s in sunfish.

But I'm happy to discuss any pull request.
