### ISSUE TITLE
Wikispaces link in the description is dead

### ISSUE THREAD

**Issue by abhinuvpitale** [thomasahle/sunfish#59]
Redirects to wikispaces error page. That link needs to be changed to appropriate web page

**Comment by thomasahle** [comment]
I can't find the link. Do you wanna submit a pull request? Thank you!

**Comment by Recursing** [comment]
I couldn't find how to change the project description via pull request.

Anyway, the current wiki at chessprogramming.org doesn't have a page for Sunfish, but the old one is still accessible via https://web.archive.org/web/20180823081822/http://chessprogramming.wikispaces.com/Sunfish

**Comment by thomasahle** [comment]
Right, I forgot about that one :-)
I wonder if there is a way to migrate the old page to https://www.chessprogramming.org .

**Comment by abhinuvpitale** [comment]
The announcement there says that they are on a process to migrate to new host, so should we wait ?

**Comment by Recursing** [comment]
> You may still miss former pages, in particular people and engine pages, but most programming stuff is finished, and you will notice progress almost daily. 

Looking at the recent changes https://www.chessprogramming.org/index.php?title=Special:RecentChanges&limit=500&days=30 it seems to be almost all the work of one guy doing it by hand D:

**Comment by thomasahle** [comment]
Yeah, progress is painfully slow.
Maybe just copying the old wiki page to the Github wiki would be beneficial...

**Comment by Recursing** [comment]
I copied the page to the github wiki, maybe it could also be a place for more explanations of stuff like null-move pruning and MTD(bi)

**Comment by thomasahle** [comment]
Looks like we are back: https://www.chessprogramming.org/Sunfish
