### ISSUE TITLE
Sunfish lost on time after 8 minutes thinking about only 3 legal moves

### ISSUE THREAD

**Issue by unformatt** [thomasahle/sunfish#60]
![image](https://user-images.githubusercontent.com/157132/58973512-23f6e680-878e-11e9-8161-6d4445835e5a.png)

**Comment by Recursing** [comment]
Sorry, I think it crashed, please file these issues at https://github.com/Recursing/sunfish_rs

**Comment by thomasahle** [comment]
Thanks @Recursing
