### ISSUE TITLE
Sunfish loses for time when it will perform a mate on the contrary

### ISSUE THREAD

**Issue by pmcastro** [thomasahle/sunfish#64]
[sunfish.zip](https://github.com/thomasahle/sunfish/files/3551338/sunfish.zip)
[Event "Arena Tournament 1311"]
[Site "DESKTOP-AMD"]
[Date "2019.06.25"]
[Round "7"]
[White "Pyotr 0.6 AM"]
[Black "Sunfish 2019.06.02"]
[Result "1-0"]
[WhiteElo "868"]
[BlackElo "2200"]
[WhiteType "program"]
[BlackType "program"]
[ECO "A40"]
[Opening "Queen's Pawn"]
[Variation "1...e6 2.c4"]
[TimeControl "40/180:40/180:40/180"]
[Time "07:46:35"]
[Termination "time forfeit"]
[PlyCount "95"]

1. d4 e6 2. c4 c6 3. e4 d5 4. e5 dxc4 5. Bxc4 c5 6. dxc5 Qxd1+ { (6. ...
Dxd1+ 7.Rxd1 Axc5 8.Ae3 Axe3 9.fxe3 Cc6) -0.09/7 5 } 7. Kxd1 Bxc5 { (7. ...
Axc5 8.Ae3 Axe3 9.fxe3 Cc6 10.Cf3 Cge7) -0.26/7 6 } 8. Be3 Nd7 { (8. ...
Cd7 9.Cf3 Ce7 10.Axc5 Cxc5) -0.10/7 8 } 9. Bxc5 Nxc5 { (9. ... Cxc5 10.Cc3
Ad7 11.b4 Ca4 12.Cxa4 Axa4+) -0.24/7 4 } 10. Kc1 Bd7 { (10. ... Ad7 11.Cf3
0-0-0 12.Td1) -0.08/6 3 } 11. Nc3 O-O-O { (11. ... 0-0-0 12.Cf3 Rb8 13.Td1)
-0.10/6 3 } 12. b4 Bc6 { (12. ... Ac6 13.Cf3 Cd3+ 14.Axd3 Txd3 15.Rc2 Td8)
+0.37/7 7 } 13. bxc5 Bxg2 { (13. ... Axg2 14.Cb5 Axh1 15.Cd6+ Rb8 16.Cxf7
Td4) +1.20/7 3 } 14. Nb5 Kb8 { (14. ... Rb8 15.Cd6 Ch6 16.Cxb7 Td4 17.Axe6
Axh1) +0.66/6 4 } 15. Nd6 Nh6 { (15. ... Ch6 16.f3 Axh1 17.Tb1 Ra8 18.Tb5)
+1.18/6 3 } 16. Nxb7 Kxb7 { (16. ... Rxb7 17.Tb1+ Rc8 18.Aa6+ Rc7 19.Ab7
Axb7) +3.40/7 4 } 17. Rb1+ Ka8 { (17. ... Ra8) +4.16/7 4 } 18. a4 Bxh1 {
(18. ... Axh1 19.f3 Cf5 20.Ab5 a6 21.Axa6 Ag2) +4.80/7 7 } 19. a5 Ng4 {
(19. ... Cg4 20.f4 Ce3 21.Aa2 Ad5 22.Ab3 Axb3 23.Txb3) +5.54/6 2 } 20. Ne2
Nxf2 { (20. ... Cxf2 21.a6 Ae4 22.Tb5 Td1+) +6.56/5 2 } 21. Nc3 Rd4 { (21.
... Td4 22.Ab5 Ag2 23.a6) +6.48/6 3 } 22. Bxe6 fxe6 { (22. ... fxe6 23.Cb5
Td1+ 24.Rb2 Td2+ 25.Ra1) +8.41/6 2 } 23. Kc2 Bc6 { (23. ... Ac6 24.Tg1 Tg8
25.Tf1 Tf8 26.a6) +8.88/6 8 } 24. Rg1 g6 { (24. ... g6 25.Te1 Te8) +9.37/5
1 } 25. Kc1 Rc4 { (25. ... Tc4 26.Rb2 Tb8+ 27.Rc2 Txc5 28.Te1) +9.58/6 6 }
26. Rg3 Rxc5 { (26. ... Txc5) +10.52/6 1 } 27. a6 Rxe5 { (27. ... Txe5)
+10.82/6 2 } 28. Rg1 Ra5 { (28. ... Ta5) +11.48/5 1 } 29. Kc2 Rh5 { (29.
... Th5 30.Te1 Te8 31.Cd1 Txh2 32.Cxf2 Txf2+) +11.52/5 1 } 30. Re1 Re8 {
(30. ... Te8 31.h4 Txh4 32.Rb1 Th2 33.Te5 Rb8) +11.66/6 2 } 31. Kd2 Rxh2 {
(31. ... Txh2 32.Rc2 Rb8 33.Rb1 e5) +12.34/6 2 } 32. Re2 Kb8 { (32. ... Rb8
33.Re1 Cd3+ 34.Rf1) +12.35/4 1 } 33. Kc2 e5 { (33. ... e5 34.Rb1 Th1+
35.Rb2 Th2 36.Rb1) +12.58/6 2 } 34. Rd2 h6 { (34. ... h6 35.Rb1 Th1+ 36.Rb2
Th2) +12.86/5 1 } 35. Re2 e4 { (35. ... e4 36.Te1 e3 37.Rb1) +12.81/6 2 }
36. Kd2 Rf8 { (36. ... Tf8 37.Rc1 Tf3 38.Tb2+ Ra8) +13.18/5 1 } 37. Kc2 Rf3
{ (37. ... Tf3 38.Td2) +12.80/6 6 } 38. Rd2 Rd3 { (38. ... Td3 39.Txd3
exd3+ 40.Rc1) +12.94/5 1 } 39. Rxd3 exd3+ { (39. ... exd3+ 40.Rb2 Ce4+
41.Ra1 d2 42.Cd1) +13.11/6 0 } 40. Kc1 Rh1+ { (40. ... Th1+ 41.Rd2)
+13.20/6 0 } 41. Kd2 Ne4+ { (41. ... Ce4+ 42.Rxd3 Th3+ 43.Rc2 Txc3+ 44.Rb2)
+13.56/8 5 } 42. Nxe4 Bxe4 { (42. ... Axe4 43.Re3 Th2 44.Rxe4 d2 45.Re5 d1D
46.Rf6) +16.85/8 4 } 43. Ke3 Rh2 { (43. ... Th2 44.Rxe4 d2 45.Re5 d1D
46.Rf6 Db1) +17.10/7 4 } 44. Kxe4 d2 { (44. ... d2 45.Re5 Tf2 46.Rd6 d1D+
47.Rc5 Dd3 48.Rb4) +17.66/8 4 } 45. Kd5 d1=Q+ { (45. ... d1D+ 46.Re5 Tf2
47.Re4 Dd2 48.Re5 Dd3 49.Re6) +17.92/8 15 } 46. Ke6 Rf2 { (46. ... Tf2
47.Re5) +18.00/7 12 } 47. Ke7 Kc7 { (47. ... Rc7 48.Re8) +M355/9 3 } 48.
Ke8 { Negras pierden por tiempo } 1-0

**Comment by pmcastro** [comment]
It seems as if he finds mate in a depth, then he begins a new depth and does not finish it.

This does not always happen, it is approximately 5-10%

**Comment by thomasahle** [comment]
This might be related to issue #63?

**Comment by pmcastro** [comment]
Yes, it seems to be the same.

I went here in github to report the problem that I had encountered, so I saw a message that looked like the same problem, but I wasn't sure and opened a new post, maybe I should have answered in the other thread.

In my case the problem occurred when sunfish is playing a game with 40/4 CCRL time control and on the Arena interface. I've seen the problem whenever sunfish is going to give a mate, not when it's going to receive it.

It is possible that what you say happens, the first iterations the engine quickly shows the information, goes to the next and takes a long time to respond and loses time.

In my case, I check within an iteration if the time has elapsed every x nodes, if you don't do this check, maybe you could not go to the next iteration if you already have a mate evaluation.

**Comment by thomasahle** [comment]
I don't have a great explanation for why sunfish needs so many more nodes once it reaches a certain depth in these positions.
However, I've pushed an update, commit 386f578, which fixes this in the case where it has found a mate.
