### ISSUE TITLE
Small bug - castling and pawns

### ISSUE THREAD

**Issue by Elliot-Cocks** [thomasahle/sunfish#66]
Currently, if a king is in check from a pawn, say on d7 for example, the black king can still castle kingside. The tuple on line 148 of sunfish.py should also include self.kp + 1 and self.kp - 1

**Comment by thomasahle** [comment]
That's interesting, do you have an example FEN that shows this bug?
Ideally, stuff like this should be caught by perft tests in https://github.com/thomasahle/sunfish/blob/master/tests/queen.fen .

**Comment by Elliot-Cocks** [comment]
Position with black to move, in check from a pawn on d7:
rnbqk2r/pppPppbp/5np1/8/8/8/PPPP1PPP/RNBQKBNR b KQkq - 0 4

Position after black has castled:
rnbq1rk1/pppPppbp/5np1/8/8/8/PPPP1PPP/RNBQKBNR w KQ - 0 4

Here white should be able to "capture" on e8 to prevent this action

**Comment by thomasahle** [comment]
Very nice! I added a test and pushed a fix. Thank you!

**Comment by thomasahle** [comment]
@Elliot-Cocks, can I ask how you found the bug?

**Comment by Elliot-Cocks** [comment]
@thomasahle I was programming my own chess engine using "king passant" and when writing the pawn captures I discovered that kings could castle out of pawn checks as they left the square vacant.
