### ISSUE TITLE
FICS broken

### ISSUE THREAD

**Issue by iw6dgm** [thomasahle/sunfish#67]
Hi,
trying to connect Sunfish to my local FICS (free internet chess server) via xboard:
`xboard -size Medium -zp -fd ~/chess/sunfish -ics -icshost $FICS_LOCAL_IP -icsport 5000 -icshelper ~/bin/timeseal -icslogon ~/chess/sunfish.ini -fcp "python -m xboard"`

(sunfish folder is a symlink to the git repo)

Just after my first move (Sunfish playing as Black) I get several
`xboard: Error writing to first chess program: Broken pipe` and xboard exits

Tried with `pypy -u`, `python xboard.py` and other flavours (e.g. shell scripts) with no luck.

xboard 4.8.0
FICS server 2.2.x-DEVEL

**Comment by thomasahle** [comment]
Hi iw6dgm, the xboard module is unfortunately not quite stable. Are you able to try the uci module instead, perhaps using some intermediate layer?

**Comment by iw6dgm** [comment]
Sure, I'll give it a go via `polyglot` middleware

**Comment by iw6dgm** [comment]
No luck with `uci` either but I think the error is much more understandable
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/joshua/git/sunfish/uci.py", line 131, in <module>
    main()
  File "/home/joshua/git/sunfish/uci.py", line 81, in main
    opp_time = int(params[i])
NameError: name 'i' is not defined
```
(tried using `uci2wb` middleware - instead of `polyglot` - as it seems to be the better, up2date adapter for UCI and XBoard)

**Comment by thomasahle** [comment]
Thank you! Apparently a previous commit broke uci and the uci unit-tests I thought were around were completely missing!

Both uci and testing should work now. Thank you for noticing!
