### ISSUE TITLE
Probably unnecessary code

### ISSUE THREAD

**Issue by aceking007** [thomasahle/sunfish#68]
sunfish.py
145 # Pawn move, double move and capture
146  if p == 'P' and d in (N, N+N) and q != '.': break
------------------------------------------------------
Line 146 is probably unnecessary - may comment it out or delete it to make the program shorter

**Comment by thomasahle** [comment]
Interesting! But isn't this line responsible for avoiding pawns capturing when moving forward?

**Comment by aceking007** [comment]
Yep. Didn't see that before.
