### ISSUE TITLE
Add more features to UCI.py

### ISSUE THREAD

**Issue by jlrdh** [thomasahle/sunfish#70]
Hello, I encountered this issue with Sunfish:
* Start position r2qkbnr/p1pnP1p1/8/5p1p/3P2b1/2p2N2/PPPB1PPP/R2QKB1R w KQkq - 0 1
with Sunfish set to play Black

When White plays e7d8q in cutechess, Sunfish does not play at all.

* With the same FEN and Sunfish is set to play white, Sunfish plays exd8=Q+ , but then when the cutechess uci command sends 
>>> position fen r2qkbnr/p1pnP1p1/8/5p1p/3P2b1/2p2N2/PPPB1PPP/R2QKB1R w KQkq - 0 1 moves e7d8q e8d8 

Sunfish disconnects. 

Hope that reporting this issue will help improve the Sunfish engine

**Comment by thomasahle** [comment]
Thank you.
As it is now, Sunfish doesn't really support UCI. There is only some very preliminary code submitted by @ryanhs back in 2017.
One feature it doesn't support is mixing `position fen` and `moves`.
On the other hand, mixing `position startpos` and `moves` is actually supported, so it shouldn't be too hard to add this feature.

**Comment by thomasahle** [comment]
The latest version now supports the whole uci standard.
