### ISSUE TITLE
how to setup Sunfish with CuteChess ?

### ISSUE THREAD

**Issue by tissatussa** [thomasahle/sunfish#78]
i'm not a beginner with python and chess engines .. i see the file uci.py but how to use it ?  :: which command should be entered in the CuteChess GUI ?  i prefer the UCI protocol.  I'm using Xubuntu 20.04

**Comment by thomasahle** [comment]
Check the instructions at https://github.com/thomasahle/sunfish#run-it
It's better to use xboard now, since the uci.py module isn't that stable. However you can try it out if you'd like.

**Comment by thomasahle** [comment]
There is now an engines.json file, which should hopefully make it easy to integrate with cutechess.
