### ISSUE TITLE
Cant seem to play as black

### ISSUE THREAD

**Issue by tamirha2530** [thomasahle/sunfish#81]
Can anyone give an explanation about how to play as black with the engine?
Thank you.

**Comment by afentev** [comment]
There is no built-in possibility to play as black. But you can easily change several parts of the code to do this. Firstly, you'll need to make a computer to make the first turn. Secondly, you should change the en-passant rule; you can do this by modifying 147's line in the sunfish.py. The point is this line controls if a black pawn is on the 7'th rank. So if the computer plays as white you should check not the 7'th rank, but the second. Hope this will be useful

**Comment by thomasahle** [comment]
You can now play as black by running `python fancy.py` instead of `sunfish.py`.

**Comment by tissatussa** [comment]
the newest "version 2023" seems to be able to play with Black !? And it supports UCI .. nice !
