### ISSUE TITLE
Add `#!/usr/bin/env pypy3` to top of fancy.py

### ISSUE THREAD

**Issue by misterbeebee** [thomasahle/sunfish#84]
`sunfish.py` has a shebang line, but `fancy.py` doesn't.

To make `fancy.py` run out-of-the-box,
add `#!/usr/bin/env pypy3` to top of `fancy.py`.`

(`fancy.py doesn't work with Python2 `pypy`, so requires `pypy3`.  `sunfish.py` does run under Python2 `pypy`)

**Comment by misterbeebee** [comment]
Correction: I think `fancy.py` will work with `pypy`; `pypy3` not required.

**Comment by thomasahle** [comment]
This is fixed in the latest version. Thanks.
