### ISSUE TITLE
How to Run Sunfish...

### ISSUE THREAD

**Issue by SLW2K** [thomasahle/sunfish#89]
I was told by someone else here on GitHub that "python chess programs" could be run by just downloading and using PYPY (I don't need to install Python). So I grabbed PyPy 3.8 (https://www.pypy.org/download.html) for Windows 64-bit.

I have PyPy 3.8, and I have your Sunfish.zip, and I have the Python Chess 1.7.0.zip. I have PyPy 3.8 unzipped to C:\PYPY on my hard drive. Now what do I do?

Shawn

**Comment by thomasahle** [comment]
In your terminal, you should write `path_to_pypy` `path_to_sunfish.py`. 

If that doesn't answer your question, I'm afraid I can't really help. I'm not on Windows. But there are some videos you could watch like this: https://www.youtube.com/watch?v=Kn1HF3oD19c

You can also play against sunfish on Lichess.

**Comment by SLW2K** [comment]
Thanks Thomas, I'll let you know if I get it running. I have been playing it on Lichess, the Rust version - fun opponent. Would you ever consider doing a Java version?

Shawn
