### ISSUE TITLE
sunfish can't play white?

### ISSUE THREAD

**Issue by null-Exception1** [thomasahle/sunfish#92]
I tried a couple times by rotating board before it started searching, but still gives weird evals and errors meaning its still playing black

**Comment by thomasahle** [comment]
It can definitely play as white. Can you give more details on what you tried?

**Comment by Great-error** [comment]
> I tried a couple times by rotating board before it started searching, but still gives weird evals and errors meaning its still playing black

Any updates?

**Comment by thomasahle** [comment]
@null-Exception1 Can you show the commands you ran? And what output you got?

**Comment by feldnerd** [comment]
> It can definitely play as white. Can you give more details on what you tried?

@thomasahle What is the simplest way to make it play as white?

**Comment by thomasahle** [comment]
Just run `fancy.py`.

**Comment by null-Exception1** [comment]
solved it. all good.
